# Generated by Django 3.1.5 on 2021-01-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='count',
            field=models.IntegerField(verbose_name='Number of posts'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='hashtag'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='follower',
            field=models.IntegerField(verbose_name='Follower'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='follows',
            field=models.IntegerField(verbose_name='Follow'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(verbose_name='Number of posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(verbose_name='How nice'),
        ),
    ]
